name: Build and Deploy Marp to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      # Génère un HTML unique pour la page d’accueil
      - name: Build slides
        run: |
          mkdir -p dist
          marp slides.md -o dist/index.html --allow-local-files ${THEME:+--theme-set $THEME}
        env:
          # si tu as un style custom, mets "style.css" (commité à la racine)
          THEME: ""

      # Copie les assets (images, css…) utilisés par la présentation
      - name: Copy assets
        run: |
          shopt -s extglob
          # copie tout sauf dist/ et .git/ et .github/
          rsync -av --exclude 'dist' --exclude '.git' --exclude '.github' ./ dist/
          # garde index.html généré par Marp
          mv dist/index.html dist/__index__.html
          # s’il existe un slides.md, on évite de l’écraser : on remet le index
          mv dist/__index__.html dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
